import assert from 'node:assert/strict';
import { test } from 'node:test';

import { agreementsSql, createResolver, parseCsv, readAgreements } from './partnerships-csv.mjs';

const catalogue = [
  ['unimi', 'University of Milan', 'IT', 'Milan', 'https://www.unimi.it', 'unimi.it studenti.unimi.it', 'I  MILANO01', 1],
  ['heidelberg', 'Heidelberg University', 'DE', 'Heidelberg', 'https://www.uni-heidelberg.de', 'uni-heidelberg.de', 'D  HEIDELB01', 1],
  ['utoronto', 'University of Toronto', 'CA', 'Toronto', 'https://www.utoronto.ca', 'utoronto.ca', '', 0],
];
const resolve = createResolver(catalogue);

test('parses quoted CSV fields', () => {
  assert.deepEqual(parseCsv('a,b\n"x, y","say ""hi"""\r\n\n'), [
    ['a', 'b'],
    ['x, y', 'say "hi"'],
  ]);
});

test('resolves catalogue ids, Erasmus codes and domains', () => {
  assert.equal(resolve('unimi'), 'unimi');
  assert.equal(resolve('d heidelb01'), 'heidelberg');
  assert.equal(resolve('https://www.utoronto.ca/exchange'), 'utoronto');
  assert.equal(resolve('Heidelberg'), null);
});

const csv = `home_university,partner_university,agreement_type,department,isced_codes,languages,places,academic_year,source_url
I  MILANO01,D  HEIDELB01,Erasmus+,Department of Biosciences,051;0512,de;en,2,2026/27,https://www.unimi.it/en/erasmus-partners.pdf
unimi,utoronto,bilateral,,,en,,2026/27,https://www.unimi.it/en/overseas
unimi,unimi,erasmus,,,,,,https://www.unimi.it
unimi,nowhere.example,other,,4a,english,0,,not-a-link
`;

test('validates rows and reports problems by line', () => {
  const { agreements, errors } = readAgreements(csv, resolve);
  assert.equal(agreements.length, 2);
  assert.deepEqual(agreements[0], {
    home: 'unimi',
    partner: 'heidelberg',
    type: 'erasmus',
    department: 'Department of Biosciences',
    isced: ['051', '0512'],
    levels: [],
    languages: ['de', 'en'],
    languageLevel: '',
    places: 2,
    academicYear: '2026/27',
    sourceUrl: 'https://www.unimi.it/en/erasmus-partners.pdf',
  });
  assert.equal(errors.length, 2);
  assert.match(errors[0], /^Line 4: home and partner are the same university/);
  assert.match(errors[1], /^Line 5: unknown partner.*agreement_type|^Line 5: unknown partner/);
  assert.match(errors[1], /source_url/);
  assert.match(errors[1], /isced_codes/);
  assert.match(errors[1], /languages/);
  assert.match(errors[1], /places/);
  assert.deepEqual(readAgreements('home_university,partner_university\n', resolve).errors, [
    'Missing column "agreement_type".',
    'Missing column "source_url".',
  ]);
});

test('generates escaped, idempotent SQL marked verified', () => {
  const { agreements } = readAgreements(csv.replace('Department of Biosciences', "Dipartimento d'Informatica"), resolve);
  const sql = agreementsSql(agreements, { today: '2026-09-27', origin: 'list.csv' });
  assert.match(sql, /^-- Generated by scripts\/import-partnerships\.mjs from list\.csv on 2026-09-27/);
  assert.match(sql, /'Dipartimento d''Informatica'/);
  assert.match(sql, /on conflict \(home_university_id, partner_university_id, agreement_type, coalesce\(home_department_id::text, ''\)\)/);
  assert.equal(sql.match(/insert into public\.partnerships/g)?.length, 2);
  assert.match(sql, /'admin', 'https:\/\/www\.unimi\.it\/en\/overseas', true, '2026-09-27'\)/);
});
