// Generates supabase/seed.sql from src/data/countries.json and
// src/data/universities.json so the app's bundled catalogue and the database
// always list the same universities. Usage: npm run gen:seed
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url);
const countries = JSON.parse(readFileSync(new URL('src/data/countries.json', root), 'utf8'));
const universities = JSON.parse(readFileSync(new URL('src/data/universities.json', root), 'utf8'));

const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;
const array = (values) => (values.length ? `array[${values.map(quote).join(', ')}]::text[]` : `'{}'::text[]`);
const BATCH = 500;

const parts = ['-- Generated by scripts/generate-seed.mjs. Do not edit by hand.', ''];

parts.push(
  'insert into public.countries (code, name, region, erasmus_programme) values',
  Object.entries(countries)
    .map(([code, [name, region, erasmus]]) => `  (${quote(code)}, ${quote(name)}, ${quote(region)}, ${erasmus === 1})`)
    .join(',\n'),
  'on conflict (code) do update set name = excluded.name, region = excluded.region, erasmus_programme = excluded.erasmus_programme;',
  '',
);

for (let start = 0; start < universities.length; start += BATCH) {
  const rows = universities.slice(start, start + BATCH).map(([id, name, code, city, website, domains, erasmusCode, featured]) => {
    const [countryName, region, erasmus] = countries[code];
    return `  (${[id, name, city, countryName, code, region, website].map(quote).join(', ')}, ${array(domains ? domains.split(' ') : [])}, ${erasmusCode ? quote(erasmusCode) : 'null'}, ${erasmus === 1}, ${featured === 1})`;
  });
  parts.push(
    'insert into public.universities (id, name, city, country, country_code, region, website, email_domains, erasmus_code, erasmus_programme, featured) values',
    rows.join(',\n'),
    'on conflict (id) do update set name = excluded.name, city = excluded.city, country = excluded.country,',
    '  country_code = excluded.country_code, region = excluded.region, website = excluded.website,',
    '  email_domains = excluded.email_domains, erasmus_code = excluded.erasmus_code,',
    '  erasmus_programme = excluded.erasmus_programme, featured = excluded.featured;',
    '',
  );
}

writeFileSync(new URL('supabase/seed.sql', root), parts.join('\n'));
console.log(`Wrote ${Object.keys(countries).length} countries and ${universities.length} universities to supabase/seed.sql`);
