// Generates supabase/seed.sql from src/data/universities.json so the app's
// offline catalogue and the database always list the same universities.
// Usage: npm run gen:seed
import { readFileSync, writeFileSync } from 'node:fs';

const universities = JSON.parse(readFileSync(new URL('../src/data/universities.json', import.meta.url), 'utf8'));
const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;
const array = (values) => `array[${values.map(quote).join(', ')}]::text[]`;

const rows = universities.map(
  (u) =>
    `  (${[u.id, u.name, u.city, u.country, u.countryCode, u.region, u.website].map(quote).join(', ')}, ${array(u.emailDomains)})`,
);

const sql = `-- Generated by scripts/generate-seed.mjs from src/data/universities.json. Do not edit by hand.
insert into public.universities (id, name, city, country, country_code, region, website, email_domains)
values
${rows.join(',\n')}
on conflict (id) do update set
  name = excluded.name,
  city = excluded.city,
  country = excluded.country,
  country_code = excluded.country_code,
  region = excluded.region,
  website = excluded.website,
  email_domains = excluded.email_domains;
`;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`Wrote ${universities.length} universities to supabase/seed.sql`);
