/**
 * World university catalogue bundled with the app (generated by
 * scripts/import-universities.mjs; ~10k universities with their email domains),
 * ordered Europe first, then Canada, Australia, other countries and the US.
 */
import countriesJson from './countries.json';
import departmentsJson from './departments.json';
import type { Department, Region, University } from './types';
import universitiesJson from './universities.json';

type Row = [string, string, string, string, string, string, string, number, number, number];
type CountryRow = [string, Region, number];

const countries = countriesJson as unknown as Record<string, CountryRow>;

export const universities: University[] = (universitiesJson as unknown as Row[]).map(
  ([id, name, countryCode, city, website, domains, erasmusCode, featured, businessSchool, verified]) => {
    const country = countries[countryCode];
    return {
      id,
      name,
      city,
      country: country?.[0] ?? countryCode,
      countryCode,
      region: country?.[1] ?? 'europe',
      website,
      emailDomains: domains ? domains.split(' ') : [],
      erasmusCode: erasmusCode || null,
      erasmus: country?.[2] === 1,
      featured: featured === 1,
      kind: businessSchool === 1 ? 'business_school' : 'university',
      verified: verified === 1,
    };
  },
);

const byId = new Map(universities.map((u) => [u.id, u]));

export function getUniversity(id: string | null | undefined): University | undefined {
  return id ? byId.get(id) : undefined;
}

export type Country = { code: string; name: string; region: Region; erasmus: boolean };

export const countryList: Country[] = Object.entries(countries)
  .map(([code, [name, region, erasmus]]) => ({ code, name, region, erasmus: erasmus === 1 }))
  .sort((a, b) => a.name.localeCompare(b.name));

export function countryName(code: string | null | undefined): string {
  return (code && countries[code]?.[0]) || code || '';
}

export function normalize(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim();
}

let searchIndex: string[] | null = null;
function index(): string[] {
  searchIndex ??= universities.map((u) => normalize(`${u.name} ${u.city} ${u.country} ${u.emailDomains.join(' ')}`));
  return searchIndex;
}

export type Scope = 'all' | 'erasmus' | 'overseas';

/** Results keep the catalogue order (Europe first); names starting with the query come first. */
export function searchUniversities(
  query: string,
  {
    region = 'all',
    scope = 'all',
    kind = 'all',
    limit = 60,
  }: { region?: Region | 'all'; scope?: Scope; kind?: University['kind'] | 'all'; limit?: number } = {},
): University[] {
  const q = normalize(query);
  const keys = index();
  const starts: University[] = [];
  const contains: University[] = [];
  for (let i = 0; i < universities.length; i++) {
    const u = universities[i];
    if (region !== 'all' && u.region !== region) continue;
    if (scope === 'erasmus' && !u.erasmus) continue;
    if (scope === 'overseas' && u.erasmus) continue;
    if (kind !== 'all' && u.kind !== kind) continue;
    if (!q) {
      contains.push(u);
    } else if (normalize(u.name).startsWith(q)) {
      starts.push(u);
    } else if (keys[i].includes(q)) {
      contains.push(u);
    }
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}

const departments = departmentsJson as unknown as Record<string, [string, Department['kind']][]>;

/** Departments listed in the curated catalogue (unverified), for universities that have them. */
export function catalogueDepartments(universityId: string): Department[] {
  const university = getUniversity(universityId);
  return (departments[universityId] ?? []).map(([name, kind], index) => ({
    id: `${universityId}-catalogue-${index}`,
    universityId,
    name,
    kind,
    iscedCodes: [],
    website: '',
    sourceUrl: university?.website ?? '',
    verified: false,
  }));
}
